services:
  app:
    build: .
    # container_name: nextjs_app
    volumes:
      - ./:/work
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=development

  db:
    image: mysql:8.0
    # container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: